/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client.view;

import client.controller.Client;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author DoQuan_User
 */
public class MainVoiceCall extends javax.swing.JFrame {

    /**
     * Creates new form MainVoiceCall
     */
    private Client client;
    
    public MainVoiceCall(Client client) {
        initComponents();
        this.client = client;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        client.startVoiceChatThread();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                client.stopVoiceChatThread();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titleOfVoiceCall = new javax.swing.JLabel();
        cancelCall = new javax.swing.JLabel();
        lbl_participant = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_titleOfVoiceCall.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_titleOfVoiceCall.setText("Voice call");

        cancelCall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons8-end-call-48.png"))); // NOI18N
        cancelCall.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelCall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelCallMouseClicked(evt);
            }
        });

        lbl_participant.setText("participant:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titleOfVoiceCall)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cancelCall))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_participant)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titleOfVoiceCall)
                .addGap(18, 18, 18)
                .addComponent(lbl_participant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(cancelCall)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelCallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelCallMouseClicked
        client.stopVoiceChatThread();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelCallMouseClicked

    
    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelCall;
    private javax.swing.JLabel lbl_participant;
    private javax.swing.JLabel lbl_titleOfVoiceCall;
    // End of variables declaration//GEN-END:variables
}
